[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.n8n"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
NODE_ENV = "production"

[environments.development.variables] 
NODE_ENV = "development"
